"""Fixed KiCad category taxonomy and LCSC -> final-category resolution.

LCSC exposes ~600 leaf categories. For PCB/KiCad use most of that detail is
noise, so we collapse it into a small fixed set of final categories
(``FINAL_CATEGORIES``). Each final category becomes exactly one KiCad symbol
library, and the set never changes at runtime — so the libraries (and the
sym-lib-table) can be created up front and KiCad never needs a restart when a
new part in a new category arrives.

``resolve_category`` maps any incoming LCSC category string onto one final
category:
  1. exact match against the hand-built ``SOURCES`` mapping (normalised),
  2. otherwise the closest match (difflib) against the known LCSC names and the
     final names, if it clears a similarity threshold,
  3. otherwise ``Uncategorized``.

Step 2 is what lets unseen variants resolve sensibly, e.g.
``"Photodiodes - SMD"`` -> the bucket that owns ``"Photodiodes"``.
"""

import re
from difflib import SequenceMatcher

# Ordered for a browsable dropdown: passives, discretes, ICs, opto, sensor,
# electromechanical, then misc, with the fallback last.
FINAL_CATEGORIES = [
    "Resistor",
    "Capacitor",
    "Inductor",
    "Transformer",
    "Crystal_Oscillator",
    "Potentiometer",
    "Filter",
    "Diode",
    "Transistor",
    "Thyristor",
    "Circuit_Protection",
    "Microcontroller",
    "Memory",
    "Logic",
    "Amplifier",
    "Interface",
    "Data_Converter",
    "Clock_Timing",
    "Power_Management",
    "Driver",
    "IC_Misc",
    "LED",
    "Display",
    "Optocoupler",
    "Sensor",
    "Connector",
    "Relay",
    "Switch",
    "Power_Module",
    "RF",
    "Audio",
    "Module",
    "Uncategorized",
]

# final category -> list of LCSC category names (top-level and leaf) that map to
# it. Built from LCSC's published category tree. Names deliberately deleted from
# the tree (no place on a PCB / in KiCad) are listed under "Uncategorized" so
# that closest-match never drags them into a real bucket.
SOURCES = {
    "Resistor": [
        "Resistors",
        "Chassis Mount Resistors",
        "Chip Resistor - Surface Mount",
        "Current Sense Resistors",
        "Resistor Kits",
        "Resistor Networks, Arrays",
        "Resistors Accessories",
        "Specialized Resistors",
        "Through Hole Resistors",
    ],
    "Capacitor": [
        "Capacitors",
        "Aluminum - Polymer Capacitors",
        "Aluminum Electrolytic Capacitors",
        "Capacitor Networks, Arrays",
        "Ceramic Capacitors",
        "Electric Double Layer Capacitors (EDLC), Supercapacitors",
        "Film Capacitors",
        "Mica and PTFE Capacitors",
        "Motor Start, Motor Run Capacitors (AC)",
        "Niobium Oxide Capacitors",
        "Silicon Capacitors",
        "Tantalum - Polymer Capacitors",
        "Tantalum Capacitors",
        "Thin Film Capacitors",
        "Trimmers, Variable Capacitors",
    ],
    "Inductor": [
        "Inductors, Coils, Chokes",
        "Adjustable Inductors",
        "Arrays, Signal Transformers",
        "Delay Lines",
        "Fixed Inductors",
        "Wireless Charging Coils",
        "Magnetics - Transformer, Inductor Components",
        "Bobbins (Coil Formers), Mounts, Hardware",
        "Ferrite Cores",
        "Magnet Wire",
    ],
    "Transformer": [
        "Transformers",
        "Audio Transformers",
        "Current Transformers",
        "Isolation Transformers and Autotransformers, Step Up, Step Down",
        "Potential Transformer",
        "Power Transformers",
        "Pulse Transformers",
        "Specialty Transformers",
        "Switching Converter, SMPS Transformers",
    ],
    "Crystal_Oscillator": [
        "Crystals, Oscillators, Resonators",
        "Crystal, Oscillator, Resonator Accessories",
        "Crystals",
        "Oscillators",
        "Pin Configurable/Selectable Oscillators",
        "Programmable Oscillators",
        "Resonators",
        "Stand Alone Programmers",
        "VCOs (Voltage Controlled Oscillators)",
    ],
    "Potentiometer": [
        "Potentiometers, Variable Resistors",
        "Adjustable Power Resistor",
        "Rotary Potentiometers, Rheostats",
        "Scale Dials",
        "Slide Potentiometers",
        "Thumbwheel Potentiometers",
        "Trimmer Potentiometers",
        "Value Display Potentiometers",
    ],
    "Filter": [
        "Filters",
        "Cable Ferrites",
        "Ceramic Filters",
        "Common Mode Chokes",
        "EMI/RFI Filters (LC, RC Networks)",
        "Feed Through Capacitors",
        "Ferrite Beads and Chips",
        "Filter Accessories",
        "Helical Filters",
        "Monolithic Crystals",
        "Power Line Filter Modules",
        "RF Filters",
        "SAW Filters",
    ],
    "Diode": [
        "Current Regulation - Diodes, Transistors",
        "Diodes",
        "Bridge Rectifiers",
        "Rectifiers",
        "RF Diodes",
        "Variable Capacitance (Varicaps, Varactors)",
        "Zener",
    ],
    "Transistor": [
        "JFETs",
        "Programmable Unijunction Transistors",
        "Special Purpose Transistors",
        "Transistors",
        "Bipolar (BJT)",
        "FETs, MOSFETs",
        "Single FETs, MOSFETs",
        "IGBTs",
    ],
    "Thyristor": [
        "Thyristors",
        "DIACs, SIDACs",
        "SCRs",
        "SCRs - Modules",
        "TRIACs",
    ],
    "Circuit_Protection": [
        "Circuit Protection",
        "Circuit breaker accessories",
        "Circuit Breakers",
        "Circuit Protection Accessories",
        "Equipment circuit breaker",
        "Fuseholders",
        "Fuses",
        "Gas Discharge Tube Arresters (GDT)",
        "Ground Fault Circuit Interrupter (GFCI)",
        "Inrush Current Limiters (ICL)",
        "Miniature Circuit Breaker",
        "Miniature leakage protection circuit breaker",
        "Miniature Residual Current Circuit Breaker",
        "Molded case circuit breakers",
        "Motor Protective Circuit Breaker",
        "Power Distribution, Surge Protectors",
        "PTC Resettable Fuses",
        "Residual Current Circuit Breaker",
        "Safety circuit breaker",
        "Surge Suppression ICs",
        "Thermal Cutoffs (Thermal Fuses)",
        "Transient Voltage Suppressors (TVS)",
        "Surge Protection Devices (SPDs)",
        "Thyristors (TSS)",
        "TVS Diodes",
        "Varistors, MOVs",
    ],
    "Microcontroller": [
        "Embedded",
        "Application Specific Microcontrollers",
        "CPLDs (Complex Programmable Logic Devices)",
        "DSP (Digital Signal Processors)",
        "FPGAs (Field Programmable Gate Array)",
        "FPGAs (Field Programmable Gate Array) with Microcontrollers",
        "Microcontrollers",
        "Microcontrollers, Microprocessor, FPGA Modules",
        "Microprocessors",
        "PLDs (Programmable Logic Device)",
        "System On Chip (SoC)",
    ],
    "Memory": [
        "Configuration PROMs for FPGAs",
        "Memory (ICs)",
        "Memory Controllers",
    ],
    "Logic": [
        "Logic",
        "Buffers, Drivers, Receivers, Transceivers",
        "Counters, Dividers",
        "FIFOs Memory",
        "Flip Flops",
        "Gates and Inverters",
        "Gates and Inverters - Multi-Function, Configurable",
        "Latches",
        "Logic Comparators",
        "Multivibrators",
        "Parity Generators and Checkers",
        "Shift Registers",
        "Signal Switches, Multiplexers, Decoders",
        "Specialty Logic",
        "Translators, Level Shifters",
        "Universal Bus Functions",
    ],
    "Amplifier": [
        "Linear",
        "Amplifiers",
        "Analog Multipliers, Dividers",
        "Linear Comparators",
        "Video Processing",
    ],
    "Interface": [
        "Interface",
        "Analog Switches - Special Purpose",
        "Analog Switches, Multiplexers, Demultiplexers",
        "CODECS",
        "Direct Digital Synthesis (DDS)",
        "Drivers, Receivers, Transceivers",
        "Encoders, Decoders, Converters",
        "I/O Expanders",
        "Interface Controllers",
        "Modems - ICs and Modules",
        "Sensor and Detector Interfaces",
        "Sensor, Capacitive Touch",
        "Serializers, Deserializers",
        "Signal Buffers, Repeaters, Splitters",
        "Signal Terminators",
        "Telecom",
        "UARTs (Universal Asynchronous Receiver Transmitter)",
        "Voice Record and Playback",
    ],
    "Data_Converter": [
        "Data Acquisition",
        "ADCs/DACs - Special Purpose",
        "Analog Front End (AFE)",
        "Analog to Digital Converters (ADC)",
        "Digital Potentiometers",
        "Digital to Analog Converters (DAC)",
        "Touch Screen Controllers",
    ],
    "Clock_Timing": [
        "Clock/Timing",
        "Application Specific Clock/Timing",
        "Clock Buffers, Drivers",
        "Clock Generators, PLLs, Frequency Synthesizers",
        "Programmable Timers and Oscillators",
        "Real Time Clocks",
    ],
    "Power_Management": [
        "Power Management (PMIC)",
        "AC DC Converters, Offline Switchers",
        "Battery Chargers ICs",
        "Battery Management",
        "Current Regulation/Management",
        "DC DC Switching Controllers",
        "Energy Metering",
        "Hot Swap Controllers",
        "OR Controllers, Ideal Diodes",
        "PFC (Power Factor Correction)",
        "Power Distribution Switches, Load Drivers",
        "Power Management - Specialized",
        "Power Over Ethernet (PoE) Controllers",
        "Power Supply Controllers, Monitors",
        "RMS to DC Converters",
        "Special Purpose Regulators",
        "Supervisors",
        "Thermal Management",
        "V/F and F/V Converters",
        "Voltage Reference",
        "Voltage Regulators - DC DC Switching Regulators",
        "Voltage Regulators - Linear + Switching",
        "Voltage Regulators - Linear Regulator Controllers",
        "Voltage Regulators - Linear, Low Drop Out (LDO) Regulators",
    ],
    "Driver": [
        "Power Driver Modules",
        "Display Drivers",
        "Full Half-Bridge (H Bridge) Drivers",
        "Gate Drivers",
        "Laser Drivers",
        "LED Drivers ICs",
        "Lighting, Ballast Controllers",
        "Motor Drivers, Controllers",
        "Isolators - Gate Drivers",
    ],
    "IC_Misc": [
        "Integrated Circuits (ICs)",
        "Specialized ICs",
        "Specialized",
        "Modules",
    ],
    "LED": [
        "LED Addressable, Specialty",
        "LED Character and Numeric",
        "LED COBs, Engines, Modules, Strips",
        "LED Color Lighting",
        "LED Dot Matrix and Cluster",
        "LED Emitters - Infrared, UV, Visible",
        "LED Indication - Discrete",
        "LED White Lighting",
        "Circuit Board Indicators, Arrays, Light Bars, Bar Graphs",
        "Display Backlights",
        "Incandescent, Neon Lamps",
        "Laser Diodes, Modules",
        "Xenon Lighting",
    ],
    "Display": [
        "Display, Monitor - LCD Driver/Controller",
        "LCD, OLED Character and Numeric",
        "LCD, OLED, Graphic",
        "Vacuum Fluorescent (VFD)",
    ],
    "Optocoupler": [
        "Isolators",
        "Digital Isolators",
        "Optocouplers, Optoisolators",
        "Logic Output Optoisolators",
        "Transistor, Photovoltaic Output Optoisolators",
        "Triac, SCR Output Optoisolators",
        "Special Purpose Isolators",
    ],
    "Sensor": [
        "Sensors, Transducers",
        "Color Sensors",
        "Color Sensors (on-board)",
        "Current Sensors",
        "Differential Pressure Transmitters",
        "Encoders",
        "Float, Level Sensors",
        "Flow Sensors",
        "Force Sensors, Load Cells",
        "Gas Sensor",
        "Humidity, Moisture Sensors",
        "IrDA Transceiver Modules",
        "LVDT Transducers (Linear Variable Differential Transformer)",
        "Magnetic Sensors",
        "Compass, Magnetic Field (Modules)",
        "Linear, Compass (ICs)",
        "Position, Proximity, Speed (Modules)",
        "Switches (Solid State)",
        "Motion Sensors",
        "Accelerometers",
        "Gyroscopes",
        "IMUs (Inertial Measurement Units)",
        "Inclinometers (ICs)",
        "Optical Motion Sensors",
        "Tilt Switches",
        "Vibration Sensors",
        "Multifunction",
        "Optical Sensors",
        "Ambient Light, IR, UV Sensors",
        "Camera Modules",
        "Distance Measuring",
        "Image Sensors, Camera",
        "Photo Detectors - CdS Cells",
        "Photo Detectors - Logic Output",
        "Photo Detectors - Remote Receiver",
        "Photodiodes",
        "Photointerrupters - Slot Type - Logic Output",
        "Photointerrupters - Slot Type - Transistor Output",
        "Photonics - Counters, Detectors, SPCM (Single Photon Counting Module)",
        "Phototransistors",
        "Reflective - Analog Output",
        "Reflective - Logic Output",
        "Particle, Dust Sensors",
        "Particulate Matter (PM) Transmitters",
        "Photoresistors",
        "Position Sensors",
        "Angle, Linear Position Measuring",
        "Pressure Sensors, Transducers",
        "Pressure Transmitters",
        "Proximity Sensors",
        "Shock Sensors",
        "Solar Cells",
        "Specialized Sensors",
        "Strain Gauges",
        "Temperature Sensors",
        "Analog and Digital Output",
        "NTC Thermistors",
        "PTC Thermistors",
        "RTD (Resistance Temperature Detector)",
        "Thermocouples, Temperature Probes",
        "Thermostats - Mechanical",
        "Thermostats - Solid State",
        "Touch Sensors",
        "Ultrasonic Receivers, Transmitters",
    ],
    "Connector": [
        "Connectors, Interconnects",
        "AC Power Connectors",
        "Plugs and Receptacles",
        "Power Entry Connector Accessories",
        "Power Entry Modules (PEM)",
        "Backplane Connectors",
        "ARINC",
        "ARINC Inserts",
        "Backplane Connector Accessories",
        "Backplane Connector Contacts",
        "Backplane Connector Housings",
        "DIN 41612",
        "Hard Metric, Standard",
        "Specialized Connectors",
        "Banana and Tip Connectors",
        "Banana and Tip Connector Accessories",
        "Banana and Tip Connector Adapters",
        "Binding Posts",
        "Jacks, Plugs",
        "Barrel Connectors",
        "Audio Connectors",
        "Barrel Connector Adapters",
        "Power Connectors",
        "Between Series Adapters",
        "Blade Type Power Connectors",
        "Blade Type Power Connector Accessories",
        "Blade Type Power Connector Assemblies",
        "Blade Type Power Connector Contacts",
        "Blade Type Power Connector Housings",
        "Card Edge Connectors",
        "Card Edge Connector Accessories",
        "Card Edge Connector Adapters",
        "Card Edge Connector Contacts",
        "Card Edge Connector Housings",
        "Edgeboard Connectors",
        "Circular Connectors",
        "Backshells and Cable Clamps",
        "Circular Connector Accessories",
        "Circular Connector Adapters",
        "Circular Connector Assemblies",
        "Circular Connector Contacts",
        "Circular Connector Housings",
        "Coaxial Connectors (RF)",
        "Coaxial Connector (RF) Accessories",
        "Coaxial Connector (RF) Adapters",
        "Coaxial Connector (RF) Assemblies",
        "Coaxial Connector (RF) Contacts",
        "Coaxial Connector (RF) Terminators",
        "Connector Adapter Kits",
        "Contacts",
        "Contacts, Spring Loaded (Pogo Pins), and Pressure",
        "Leadframe",
        "Multi Purpose",
        "D-Sub, D-Shaped Connectors",
        "Centronics Connectors",
        "D-Sub Connector",
        "D-Sub, D-Shaped Connector Accessories",
        "D-Sub, D-Shaped Connector Adapters",
        "D-Sub, D-Shaped Connector Backshells, Hoods",
        "D-Sub, D-Shaped Connector Contacts",
        "D-Sub, D-Shaped Connector Housings",
        "D-Sub, D-Shaped Connector Jackscrews",
        "D-Sub, D-Shaped Connector Terminators",
        "FFC, FPC (Flat Flexible) Connectors",
        "FFC, FPC (Flat Flexible) Connector Accessories",
        "FFC, FPC (Flat Flexible) Connector Assemblies",
        "FFC, FPC (Flat Flexible) Connector Contacts",
        "FFC, FPC (Flat Flexible) Connector Housings",
        "Fiber Optic Connectors",
        "Fiber Optic Connector Accessories",
        "Fiber Optic Connector Adapters",
        "Fiber Optic Connector Assemblies",
        "Fiber Optic Connector Housings",
        "Heavy Duty Connectors",
        "Heavy Duty Connector Accessories",
        "Heavy Duty Connector Assemblies",
        "Heavy Duty Connector Contacts",
        "Heavy Duty Connector Frames",
        "Heavy Duty Connector Housings, Hoods, Bases",
        "Heavy Duty Connector Inserts, Modules",
        "Keystone Connectors",
        "Keystone Connector Accessories",
        "Keystone Faceplates, Frames",
        "Keystone Inserts",
        "LGH Connectors",
        "Memory Connectors",
        "Inline Module Sockets",
        "Memory Connector Accessories",
        "PC Card Sockets",
        "Modular Connectors",
        "Modular/Ethernet Connector Accessories",
        "Modular/Ethernet Connector Adapters",
        "Modular/Ethernet Connector Jacks",
        "Modular/Ethernet Connector Jacks With Magnetics",
        "Modular/Ethernet Connector Plug Housings",
        "Modular/Ethernet Connector Plugs",
        "Modular/Ethernet Connector Wiring Blocks",
        "Patchbay, Jack Panel Accessories",
        "Photovoltaic (Solar Panel) Connectors",
        "Photovoltaic (Solar Panel) Connector Accessories",
        "Photovoltaic (Solar Panel) Connector Assemblies",
        "Pluggable Connectors",
        "Pluggable Connector Accessories",
        "Pluggable Connector Assemblies",
        "Rectangular Connectors",
        "Arrays, Edge Type, Mezzanine (Board to Board)",
        "Board In, Direct Wire to Board",
        "Board Spacers, Stackers (Board to Board)",
        "Free Hanging, Panel Mount",
        "Headers, Male Pins",
        "Headers, Receptacles, Female Sockets",
        "Headers, Specialty Pin",
        "Rectangular Connector Accessories",
        "Rectangular Connector Adapters",
        "Rectangular Connector Contacts",
        "Rectangular Connector Housings",
        "Spring Loaded",
        "Shunts, Jumpers",
        "Sockets for ICs, Transistors",
        "IC Sockets",
        "Socket Accessories",
        "Socket Adapters",
        "Solid State Lighting Connectors",
        "Solid State Lighting Connector Accessories",
        "Solid State Lighting Connector Assemblies",
        "Solid State Lighting Connector Contacts",
        "Terminal Blocks",
        "Barrier Blocks",
        "Din Rail, Channel",
        "Headers, Plugs and Sockets",
        "Interface Modules",
        "Panel Mount",
        "Power Distribution",
        "Specialized Terminal Blocks",
        "Terminal Block Accessories",
        "Terminal Block Adapters",
        "Terminal Block Contacts",
        "Wire to Board",
        "Terminal Junction Systems",
        "Terminal Strips and Turret Boards",
        "Terminals",
        "Barrel, Bullet Connectors",
        "Foil Connectors",
        "Housings, Boots",
        "Knife Connectors",
        "Lugs",
        "Magnetic Wire Connectors",
        "PC Pin Receptacles, Socket Connectors",
        "PC Pin, Single Post Connectors",
        "Quick Connects, Quick Disconnect Connectors",
        "Ring Connectors",
        "Screw Connectors",
        "Solder Lug Connectors",
        "Spade Connectors",
        "Specialized Connectors Terminals",
        "Terminal Accessories",
        "Terminal Adapters",
        "Turret Connectors",
        "Wire Pin Connectors",
        "Wire Splice Connectors",
        "Wire to Board Connectors",
        "USB, DVI, HDMI Connectors",
        "USB, DVI, HDMI Connector Accessories",
        "USB, DVI, HDMI Connector Adapters",
        "USB, DVI, HDMI Connector Assemblies",
    ],
    "Relay": [
        "Relays",
        "Automotive Relays",
        "Contactors (Electromechanical)",
        "Contactors (Solid State)",
        "High Frequency (RF) Relays",
        "Industrial Relays",
        "Power Relays",
        "Reed Relays",
        "Relay Modules",
        "Relay Sockets",
        "Relay Switches",
        "Relays Accessories",
        "Safety Relays",
        "Signal Relays",
        "Solid State Relays (SSR)",
    ],
    "Switch": [
        "Switches",
        "Automatic Transfer Switches",
        "Cable Pull Switches",
        "Configurable Switch Components",
        "Configurable Switch Bodies",
        "Configurable Switch Contact Blocks",
        "Configurable Switch Illumination Sources",
        "Configurable Switch Lens",
        "DIP Switches/SIP Switches",
        "Disconnect Switch Components",
        "Emergency Stop (E-Stop) Switches",
        "Foot switches",
        "Interlock Switches",
        "Keylock Switches",
        "Limit Switches",
        "Magnetic, Reed Switches",
        "Metal Dome Pot",
        "Navigation Switches, Joystick",
        "Pushbutton Switches",
        "Pushbutton Switches - Hall Effect",
        "Rocker Switches",
        "Rotary Switches",
        "Selector Switches",
        "Slide Switches",
        "Tactile Switches",
        "Thumbwheel Switches",
        "Toggle Switches",
    ],
    "Power_Module": [
        "Power Supplies",
        "Power Suppliers - Board Mount",
        "AC DC Converters",
        "DC DC Converters",
        "LED Drivers",
    ],
    "RF": [
        "RF and Wireless",
        "Attenuators",
        "Balun",
        "RF Accessories",
        "RF Amplifiers",
        "RF Antennas",
        "RF Circulators and Isolators",
        "RF Demodulators",
        "RF Detectors",
        "RF Directional Coupler",
        "RF Front End (LNA + PA)",
        "RF Misc ICs and Modules",
        "RF Mixers",
        "RF Modulators",
        "RF Multiplexers",
        "RF Power Controller ICs",
        "RF Power Dividers/Splitters",
        "RF Receivers",
        "RF Switches",
        "RF Transceiver ICs",
        "RF Transceiver Modules and Modems",
        "RF Transmitters",
        "RFID Antennas",
        "RFID Reader Modules",
        "RFID Transponders, Tags",
        "RFID, RF Access, Monitoring ICs",
        "Subscriber Identification Module (SIM) Cards",
    ],
    "Audio": [
        "Audio Products",
        "Alarms, Buzzers, and Sirens",
        "Buzzer Elements, Piezo Benders",
        "Microphones",
        "Speakers",
        "Audio Special Purpose",
    ],
    "Module": [
        "Embedded Computers",
        "Embedded Computer Interface Boards",
        "Fiber Optic Transceiver Modules",
        "Fiber Optic Receivers",
        "Fiber Optic Transmitters - Discrete",
        "Fiber Optic Transmitters - Drive Circuitry Integrated",
    ],
    # Deliberately excluded from KiCad: not board-mountable, finished units, raw
    # accessories/mechanical. Listed so closest-match keeps them out of real
    # buckets and routes them here.
    "Uncategorized": [
        "Cleaning & Janitorial",
        "Cleaning Brush",
        "Cleaning Machine",
        "Garbage Bags",
        "Rags",
        "Sponges",
        "Towels",
        "Trash Cans",
        "Wipes",
        "Power Supplies - External/Internal (Off-Board)",
        "AC DC Configurable Power Supplies (Factory Assembled)",
        "AC DC Configurable Power Supply Chassis",
        "AC DC Configurable Power Supply Modules",
        "AC DC Converters (Off-Board)",
        "AC DC Desktop, Wall Power Adapters",
        "Computer Power Supply Units",
        "DC AC Inverters",
        "DC DC Converters (Off-Board)",
        "DC Power Supplies",
        "External/Internal Power Supply Accessories",
        "Industrial, DIN Rail Power Supplies",
        "LED Drivers (Off-Board)",
        "Power over Ethernet (PoE)",
        "Uninterruptible Power Supply (UPS) Systems",
        "Single Board Computers (SBCs)",
        "Embedded Computer Accessories",
        "RF Receiver, Transmitter, and Transceiver Finished Units",
        "RF Shields",
        "RFI and EMI - Contacts, Fingerstock and Gaskets",
        "RFI and EMI - Shielding and Absorbing Materials",
        "Magnets",
        "Multi Purpose Magnets",
        "Sensor Matched Magnets",
        "Safety Light Curtains",
        "Proximity/Occupancy Sensors Finished Units",
        "Sensor Cable Accessories",
        "Sensor Cable Assemblies",
        "Sensor Interface Junction Blocks",
        "Sensor, Transducer Accessories",
        "Lenses",
        "Light Pipes",
        "Optic Spacers, Standoffs",
        "Optoelectronics Accessories",
        "Reflectors",
        "Accessories",
        "Accessories - Boots, Seals",
        "Accessories - Caps",
    ],
}


def _norm(s: str) -> str:
    """Normalise a category string for matching: lowercase, drop packaging
    qualifiers, collapse punctuation (including parentheses) to single spaces."""
    s = (s or "").lower()
    s = re.sub(r"[^a-z0-9]+", " ", s)  # punctuation (incl. parens) -> space
    s = re.sub(r"\b(smd|smt|tht)\b", " ", s)  # drop packaging tokens
    return " ".join(s.split())


# normalised LCSC name -> final category
_NORM_MAP = {}
for _final, _names in SOURCES.items():
    for _n in _names:
        _NORM_MAP[_norm(_n)] = _final
# final names are themselves valid inputs (idempotent resolution)
for _final in FINAL_CATEGORIES:
    _NORM_MAP.setdefault(_norm(_final), _final)

_FINAL_NORMS = [(f, _norm(f)) for f in FINAL_CATEGORIES]


def resolve_category(raw: str, cutoff: float = 0.62) -> str:
    """Map an arbitrary LCSC category string onto one final category.

    Exact normalised match first, then closest match (difflib) against known
    LCSC names and final names, then ``Uncategorized``.
    """
    n = _norm(raw)
    if not n:
        return "Uncategorized"
    if n in _NORM_MAP:
        return _NORM_MAP[n]

    best, best_r = "Uncategorized", 0.0
    for key, final in _NORM_MAP.items():
        r = SequenceMatcher(None, n, key).ratio()
        if r > best_r:
            best_r, best = r, final
    for final, fnorm in _FINAL_NORMS:
        r = SequenceMatcher(None, n, fnorm).ratio()
        if r > best_r:
            best_r, best = r, final

    if best_r >= cutoff:
        return best
    return "Uncategorized"
